const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('lumen_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('lumen_'+k,JSON.stringify(v))}};
const state={tab:'home',weather:'Heavy',need:null,checked:store.get('checked',false),onboarded:store.get('onboarded',false),installPrompt:null,entries:store.get('entries',[
 {day:'Thursday evening',weather:'🌧 → 🌤',text:'Felt horrible all afternoon, but dinner with A fixed something.',song:'Pink + White',tag:'Dinner with friends'},
 {day:'Tuesday, 29 September',weather:'🌫 Foggy',text:'A slow morning, cold coffee, and the kind of quiet I needed.',song:'Bloom',tag:'Time alone'},
 {day:'Sunday afternoon',weather:'☀️ Light',text:'Went outside without a plan. I want to remember the yellow light.',song:'Sunflower',tag:'Little win'}]),reset:{need:'Calm',time:'10 min',place:'Anywhere'}};
const weather=[['☀️','Light'],['🌤','Okay'],['🌙','Quiet'],['🌫','Foggy'],['🌧','Heavy'],['⛈','Overwhelmed'],['⚡','Restless']];
const needs=[['🧸','Comfort'],['🧘','Calm'],['⚡','Energy'],['🫂','Connection'],['🎨','Distraction'],['🧠','Clarity']];
const nav=[['⌂','Home','home'],['▤','Journal','journal'],['✦','Reset','reset'],['◷','Memories','memories'],['◡','Me','me']];
function layout(content){return `<section class="screen">${content}</section>${state.onboarded?`<nav class="bottom-nav">${nav.map(([i,l,t])=>`<button class="nav-btn ${state.tab===t?'active':''}" data-tab="${t}"><span class="nav-icon">${i}</span>${l}</button>`).join('')}</nav>`:''}`}
function render(){if(!state.onboarded){$('#app').innerHTML=layout(welcome());bind();return}let view={home,journal,reset,memories,me}[state.tab]();$('#app').innerHTML=layout(view);bind()}
function welcome(){return `<div class="welcome"><div class="orb">☾</div><h1>A little space for<br>your inner world.</h1><p class="sub">Check in. Keep memories. Find what helps.</p><button class="primary" data-action="begin">Make it mine →</button><button class="text-btn" data-action="demo">Explore with demo data</button><div class="tiny">Takes about 60 seconds</div></div>`}
let onboardStep=0,onboardSelected=[];
function onboarding(){let screens=[{title:'What would you like this space to help with?',items:['🌧 Understand my moods','▤ Journal more','🧸 Feel better on difficult days','🫂 Understand my social energy','🧠 Clear my head','♫ Capture life through music','✦ Remember good moments']},{title:'What brings you back to yourself?',items:['♫ Music','🎬 Films','📚 Reading','🚶 Walking','🌿 Being outside','🫂 Friends','⌂ Being alone','🎨 Making things','🏋 Exercise','🎮 Games','🍳 Cooking','😴 Rest']},{title:'Make this space yours.',items:['📜 Paper','🌸 Soft pastel','🌙 Midnight','📷 Warm film','◻ Clean minimal']}];let s=screens[onboardStep];return `<div class="onboard"><div class="progress"><i style="width:${(onboardStep+1)/3*100}%"></i></div><div class="eyebrow">A space that feels like you</div><h1 class="greeting">${s.title}</h1><p class="sub">Choose as many as you like. You can change these later.</p><div class="onboard-grid">${s.items.map(x=>`<button class="onboard-choice ${onboardSelected.includes(x)?'active':''}" data-pick="${x}">${x}</button>`).join('')}</div><button class="primary" data-action="continue">${onboardStep===2?'Open my space':'Continue'} →</button></div>`}
function home(){let checked=state.checked;return `<header class="top"><div class="eyebrow">Friday, 2 October</div><h1 class="greeting">Good evening, Yuvraj <span>🌙</span></h1><div class="week-note">✦ 3 little moments saved this week</div></header>
<div class="card weather-card"><div class="eyebrow">${checked?'Your inside weather':'A tiny check-in'}</div><h2 style="font-size:20px;margin:6px 0 13px">${checked?'🌧 Heavy + drained':'How does your inside world feel?'}</h2>${checked?`<p class="sub" style="margin:0">Sounds like today has taken a lot out of you.</p><div class="tags"><span class="tag">Energy 32%</span><span class="tag">Stress 78%</span><span class="tag">Social 38%</span></div>`:`<div class="weather-row">${weather.map(([e,n])=>`<button class="weather-pill ${state.weather===n?'active':''}" data-weather="${n}"><span>${e}</span>${n}</button>`).join('')}</div><div class="sliders"><label class="slider-line">Energy<input type="range" value="32"><output>32</output></label><label class="slider-line">Stress<input type="range" value="78"><output>78</output></label><label class="slider-line">Social battery<input type="range" value="38"><output>38</output></label><label class="slider-line">Clarity<input type="range" value="46"><output>46</output></label></div><input class="note-input" placeholder="Put it into words…"><button class="primary full" data-action="checkin">Save check-in</button>`}</div>
<h2 class="section-title">What do you need?</h2><div class="need-grid">${needs.map(([e,n])=>`<button class="need-pill ${state.need===n?'active':''}" data-need="${n}"><b>${e}</b>${n}</button>`).join('')}</div>${state.need?softLanding():''}
<h2 class="section-title">Your little world today</h2><div class="world-grid"><div class="card mini"><div>🔋 Social battery</div><div class="big">38%</div><p>You've had a people-heavy day.</p></div><div class="card mini"><div>🎧 Something that helped</div><div class="big">Music</div><p>Usually helps on overloaded days.</p></div><div class="card mini"><div>🎨 Missing ingredient</div><div class="big">Play</div><p>You haven't logged anything purely fun lately.</p></div></div>
<button class="card prompt" data-action="prompt"><div class="eyebrow">🌙 One question tonight</div><p>What took more energy today than it deserved?</p></button>`}
function softLanding(){return `<div class="card soft-landing"><div class="eyebrow">Here's your soft landing</div><h3>${state.need==='Comfort'?'Something gentle, just for you.':'A small way back to yourself.'}</h3><div class="recommend"><button class="action-card" data-action="song"><span class="icon">♫</span><div><b>Play your comfort song</b><p>Sweet Disposition · The Temper Trap</p></div></button><button class="action-card" data-tab="memories"><span class="icon">▣</span><div><b>Revisit this</b><p>The yellow-light walk · 3 months ago</p></div></button><button class="action-card" data-action="letter"><span class="icon">💌</span><div><b>A note from past you</b><p>You were worried then, too. It worked out.</p></div></button></div></div>`}
function journal(){return `<header class="top"><div class="headline-row"><div><div class="eyebrow">Journal</div><h1 class="greeting">Your life, as it felt.</h1></div><button class="ghost" data-action="new">＋</button></div></header><input class="search" placeholder="⌕  Search your world…"><div class="create-options"><button class="create-option" data-action="new"><b>✎</b>Write</button><button class="create-option" data-action="photo"><b>▣</b>Photo dump</button><button class="create-option" data-action="new"><b>✦</b>Scrapbook</button></div><h2 class="section-title">Little moments</h2><div class="timeline">${state.entries.map((e,i)=>`<article class="card entry"><div class="entry-meta"><span>${e.day}</span><span>${e.weather}</span></div>${i===0?`<div class="photo-strip"><div class="photo"></div><div class="photo"></div><div class="photo"></div></div>`:''}<p class="entry-quote">“${e.text}”</p><div class="tags"><span class="tag">♫ ${e.song}</span><span class="tag">${e.tag}</span></div></article>`).join('')}</div>`}
function reset(){return `<header class="top"><div class="eyebrow">A small reset</div><h1 class="greeting">What do you need right now?</h1><p class="sub">No fixing. Just something that might make the next moment softer.</p></header><div class="choice-grid">${[['🧸','Comfort'],['🧘','Calm'],['⚡','Energy'],['🫂','Connection'],['🧠','Clarity'],['🎨','Distraction'],['😴','Rest'],['💛','A little kindness']].map(([e,n])=>`<button class="big-choice ${state.reset.need===n?'active':''}" data-resetneed="${n}"><span style="font-size:24px">${e}</span><b>${n}</b></button>`).join('')}</div><h2 class="section-title">How much do you have?</h2><div class="segmented">${['2 min','10 min','20 min','1 hour'].map(x=>`<button class="${state.reset.time===x?'active':''}" data-time="${x}">${x}</button>`).join('')}</div><h2 class="section-title">Where are you?</h2><div class="segmented">${['Home','Work/study','Outside','Anywhere'].map(x=>`<button class="${state.reset.place===x?'active':''}" data-place="${x}">${x}</button>`).join('')}</div><button class="primary full" data-action="findreset">Find me something →</button>`}
function memories(){return `<header class="top"><div class="eyebrow">Memories</div><h1 class="greeting">Your little archive</h1><p class="sub">What you've lived through, gently returned.</p></header><h2 class="section-title">From your past</h2><div class="card memory-hero"><div class="polaroid"><div class="photo"></div><div class="polaroid-caption">Goa, six months ago ☀</div></div></div><div class="card memory-note"><div class="eyebrow">Same feeling, different day</div><p class="entry-quote" style="margin-top:9px">“Last time you felt heavy, dinner with a friend made the evening feel possible again.”</p><div class="tags"><span class="tag">🌧 → 🌤</span><span class="tag">♫ Pink + White</span></div></div><h2 class="section-title">Things you forgot you did</h2><div class="world-grid"><div class="card mini"><div class="big">✦</div><p>Asked for help when you needed it.</p></div><div class="card mini"><div class="big">🌿</div><p>Went outside on a hard afternoon.</p></div></div>`}
function me(){return `<header class="top"><div class="profile"><div class="avatar">Y</div><div><div class="eyebrow">My inner world</div><h1 class="greeting">Yuvraj</h1></div></div></header><div class="card pattern-card"><div class="headline-row"><h3>🌦 Emotional weather</h3><span class="tag">October</span></div><div class="mosaic">${['☀️','🌤','🌧','🌧','🌤','🌙','🌤','☀️','⛈','🌧','🌤','🌤','🌫','🌤','☀️','🌧','🌙','🌤','🌤','🌧','☀️'].map(x=>`<div class="day">${x}</div>`).join('')}</div></div><h2 class="section-title">Things that bring you back</h2><div class="card pattern-card"><b>🎧 Music + walk</b><p class="sub">Helped 83% of the time · Tried 6 times</p><div class="score"><i style="width:83%"></i></div></div><div class="card pattern-card"><b>📞 Calling someone close</b><p class="sub">Helped 75% of the time · Tried 4 times</p><div class="score"><i style="width:75%"></i></div></div><h2 class="section-title">Explore your world</h2><div class="menu-list"><button class="menu-item" data-action="shelf"><span>🧸 Comfort shelf</span><span>→</span></button><button class="menu-item"><span>🫂 Your social rhythm</span><span>→</span></button><button class="menu-item"><span>🎨 Mental nutrition</span><span>→</span></button><button class="menu-item" data-action="letter"><span>💌 Letters to yourself</span><span>1 sealed</span></button>${state.installPrompt?`<button class="menu-item" data-action="install"><span>📲 Install Lumen</span><span>→</span></button>`:''}<button class="menu-item"><span>⚙ Settings</span><span>→</span></button></div><p class="tiny" style="text-align:center;margin:24px 12px">Lumen supports everyday reflection. It isn't a medical or crisis service.</p>`}
function bind(){ $$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()}); $$('[data-weather]').forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;render()}); $$('[data-need]').forEach(b=>b.onclick=()=>{state.need=b.dataset.need;render();setTimeout(()=>$('.soft-landing')?.scrollIntoView({behavior:'smooth',block:'center'}),30)}); $$('input[type=range]').forEach(i=>i.oninput=()=>i.nextElementSibling.value=i.value); $$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action)); $$('[data-resetneed]').forEach(b=>b.onclick=()=>{state.reset.need=b.dataset.resetneed;render()}); $$('[data-time]').forEach(b=>b.onclick=()=>{state.reset.time=b.dataset.time;render()}); $$('[data-place]').forEach(b=>b.onclick=()=>{state.reset.place=b.dataset.place;render()}); $$('[data-pick]').forEach(b=>b.onclick=()=>{let x=b.dataset.pick;onboardSelected.includes(x)?onboardSelected=onboardSelected.filter(a=>a!==x):onboardSelected.push(x);$('#app').innerHTML=layout(onboarding());bind()}) }
function action(a){if(a==='begin'){onboardStep=0;$('#app').innerHTML=layout(onboarding());bind()}if(a==='demo'){state.onboarded=true;store.set('onboarded',true);render();toast('Your space is ready ✦')}if(a==='continue'){if(onboardStep<2){onboardStep++;onboardSelected=[];$('#app').innerHTML=layout(onboarding());bind()}else{state.onboarded=true;store.set('onboarded',true);render();toast('Welcome to your little world ✦')}}if(a==='checkin'){state.checked=true;store.set('checked',true);render();toast('Check-in saved gently ✓')}if(a==='new'||a==='photo')editor(a==='photo');if(a==='findreset')resetResult();if(a==='shelf')shelf();if(a==='letter')letter();if(a==='prompt')prompt();if(a==='song')toast('♫ Playing Sweet Disposition');if(a==='install')installApp()} 
function modal(html){$('#overlay-root').innerHTML=`<div class="overlay"><div class="sheet"><div class="handle"></div>${html}</div></div>`;$('.overlay').onclick=e=>{if(e.target.classList.contains('overlay'))closeModal()};$$('.close').forEach(b=>b.onclick=closeModal)}function closeModal(){$('#overlay-root').innerHTML=''}
function editor(photo=false){modal(`<div class="sheet-head"><div><div class="eyebrow">${photo?'Your day in 30 seconds':'New moment'}</div><h2>${photo?'A tiny photo dump':'What’s floating around?'}</h2></div><button class="close">×</button></div><div class="editor">${photo?`<button class="card" style="width:100%;height:120px;border-style:dashed;background:#eee8e2" data-upload>＋ Add 1–6 photos</button>`:''}<textarea placeholder="What would you want to remember?"></textarea><div class="editor-tools"><button class="tool">Aa Text</button><button class="tool">▣ Photo</button><button class="tool">♫ Song</button><button class="tool">⭐ Sticker</button><button class="tool">〰 Doodle</button></div><label class="tag"><input type="checkbox" id="win"> ✦ This was a little win</label><button class="primary full" id="save-entry">Save this moment</button></div>`);$('#save-entry').onclick=()=>{let text=$('.editor textarea').value.trim()||'A quiet little moment I wanted to keep.';state.entries.unshift({day:'Just now',weather:'🌤 Okay',text,song:'Sweet Disposition',tag:$('#win').checked?'Little win':'A moment'});store.set('entries',state.entries);closeModal();state.tab='journal';render();toast('Moment tucked away ✦')}}
function resetResult(){modal(`<div class="sheet-head"><div><div class="eyebrow">Your ${state.reset.time} reset</div><h2>A little room to breathe.</h2></div><button class="close">×</button></div><div class="card result-card"><div class="result-step"><b>♫</b><div><strong>Put on “Sweet Disposition”</strong><p class="sub">A song you saved as safe.</p></div></div><div class="result-step"><b>🚶</b><div><strong>Walk without checking anything</strong><p class="sub">Even to the end of the street and back.</p></div></div><div class="result-step"><b>🌬</b><div><strong>Take one slow breath</strong><p class="sub">Before you come back in.</p></div></div></div><button class="primary full" id="start-timer">Start ${state.reset.time}</button>`);$('#start-timer').onclick=()=>{$('.sheet').innerHTML=`<div class="handle"></div><div style="text-align:center;padding:35px 0"><div class="eyebrow">Your reset is in motion</div><div style="font-size:68px;margin:25px">🌿</div><div class="timer">09:59</div><p class="sub">You don't need to do this perfectly.</p><button class="primary" id="finish">I'm back</button></div>`;$('#finish').onclick=feedback}}
function feedback(){ $('.sheet').innerHTML=`<div class="handle"></div><div style="text-align:center;padding:25px 0"><div style="font-size:48px">✦</div><h2 style="margin:13px">How are you feeling now?</h2><div class="choice-grid">${['😞 Worse','😐 Same','🙂 Better','😊 Much better'].map(x=>`<button class="big-choice result-feedback">${x}</button>`).join('')}</div></div>`;$$('.result-feedback').forEach(b=>b.onclick=()=>{closeModal();toast('Noted. Lumen will remember what helps.');})}
function shelf(){modal(`<div class="sheet-head"><div><div class="eyebrow">Your soft landing</div><h2>Comfort shelf</h2></div><button class="close">×</button></div><p class="sub" style="margin-bottom:16px">Little things that feel like home.</p><div class="shelf"><div class="shelf-item"><div class="emoji">♫</div><p>Sweet Disposition</p><small>Sounds like home</small></div><div class="shelf-item"><div class="emoji">📷</div><p>Yellow light in Goa</p><small>Worth remembering</small></div><div class="shelf-item"><div class="emoji">💌</div><p>Things are weird, but we're okay.</p><small>From past you</small></div><div class="shelf-item"><div class="emoji">🫂</div><p>Call A.</p><small>My people</small></div></div><button class="primary full" onclick="toast('Add comfort — ready for your next keepsake')">＋ Add comfort</button>`)}
function letter(){modal(`<div class="sheet-head"><div><div class="eyebrow">From past you</div><h2>A letter found you 💌</h2></div><button class="close">×</button></div><div class="card memory-note" style="padding:25px"><p class="entry-quote" style="font-size:25px">Hey you,<br><br>You were worried then, too. It worked out—not perfectly, but enough. Drink some water, put on that song, and let tonight be small.<br><br>Love, you.</p></div><button class="primary full" onclick="closeModal();toast('Letter saved to your shelf')">Keep this close</button>`)}
function prompt(){modal(`<div class="sheet-head"><div><div class="eyebrow">One question tonight</div><h2>What took more energy than it deserved?</h2></div><button class="close">×</button></div><div class="editor"><textarea placeholder="Just a sentence is enough…"></textarea><button class="primary full" id="save-prompt">Save for tonight</button></div>`);$('#save-prompt').onclick=()=>{closeModal();toast('Tonight, remembered 🌙')}}
function toast(t){let e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2400)}
async function installApp(){if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;render()}
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;if(state.onboarded&&state.tab==='me')render()});
window.addEventListener('appinstalled',()=>{state.installPrompt=null;toast('Lumen is now on your home screen ✦')});
if('serviceWorker' in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
window.closeModal=closeModal;window.toast=toast;render();
