// Working journal tools, context-aware resets, games, and personal insights.
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const baseHome = home, baseMe = me, baseReset = reset, baseAction = action, baseBind = bind, baseClose = closeModal;
const check = store.get('checkin', {weather:'Heavy',energy:32,stress:78,socialBattery:38,clarity:46,note:''});
state.weather = check.weather;
state.attempts = store.get('attempts', []);
state.social = store.get('social', []);
state.nutrition = store.get('nutrition', []);
state.rotation = 0;
let resetTimer = null, draft = null, activeReset = null;
const songs = [
 {title:'Pink + White',artist:'Frank Ocean',id:'3xKsf9qdS1CyvXSMEid6g8'},
 {title:'Sunflower',artist:'Post Malone, Swae Lee',id:'0RiRZpuVRbi7oqRdSMwhQY'},
 {title:'Sweet Disposition',artist:'The Temper Trap',id:'5RoIXwyTCdyUjpMMkk4uPd'}
];
const activities = [
 ['warm','Comfort','☕','A warm little ritual','Make a warm drink. Hold the cup and notice its warmth. Sit somewhere comfortable.',['Home','Work/study'],2],
 ['letter','Comfort','💌','Borrow some kindness','Read a letter from past you, then write one kind sentence to tomorrow-you.',['Anywhere'],2],
 ['movie','Comfort','🎬','A familiar scene','Watch a scene from a film you already love. Let familiar things be enough tonight.',['Home'],10],
 ['cozy','Comfort','🧸','Make a soft corner','Find a blanket or soft layer, lower your lights, and put your phone out of reach.',['Home'],2],
 ['ground','Calm','🌿','5–4–3–2–1 grounding','Notice 5 things you can see, 4 you can feel, 3 you can hear, 2 you can smell, and 1 you can taste.',['Anywhere'],2],
 ['breath','Calm','🌬','Breathe with a little circle','Follow the circle: breathe in gently for 4 seconds and breathe out for 6. Stop if uncomfortable.',['Anywhere'],2],
 ['nature','Calm','🍃','Look for quiet details','Find a plant, tree, or patch of sky. Notice its colours and shapes without needing to describe them.',['Outside','Home'],2],
 ['unclench','Calm','👐','Let your shoulders drop','Unclench your jaw. Rest your hands. Slowly roll your shoulders, then sit quietly for a moment.',['Anywhere'],2],
 ['move','Energy','🚶','A change of pace','Walk at a comfortable pace. Notice three things you usually walk past.',['Outside'],2],
 ['stretch','Energy','🙆','Wake up gently','Stand if comfortable. Stretch your arms, roll your shoulders, and gently march in place.',['Anywhere'],2],
 ['water','Energy','💧','Water and daylight','Have a glass of water and move nearer a window. Let your eyes rest from the screen.',['Home','Work/study'],2],
 ['dance','Energy','💃','A tiny dance break','Put on a song you like and move in whatever way feels good. No choreography needed.',['Home'],2],
 ['message','Connection','💬','Send a small hello','Message someone you trust: “Thinking of you. How has your day been?” No perfect opening needed.',['Anywhere'],2],
 ['call','Connection','📞','A familiar voice','Ask someone close if they have a few minutes to talk. Tell them one small thing about your day.',['Home','Outside'],10],
 ['thanks','Connection','💛','Tell someone what mattered','Send a specific thank-you to someone who made a moment easier.',['Anywhere'],2],
 ['company','Connection','🫂','Share a little space','Ask a friend for a short walk or cup of tea. You can keep the conversation light.',['Home','Outside'],20],
 ['dump','Clarity','✎','Get the swirl onto paper','Write everything on your mind without organising it. Circle the one thing that needs attention first.',['Anywhere'],2],
 ['sort','Clarity','🗂','Mine, later, not mine','Divide your thoughts into three lists: what I can do, what can wait, and what is outside my control.',['Anywhere'],2],
 ['desk','Clarity','🧺','Clear one small surface','Choose just one corner of your space. Put away five things, then pause.',['Home','Work/study'],2],
 ['next','Clarity','🧭','One next step','Choose one task. Write its smallest next action—not the whole plan. Start only that.',['Anywhere'],2],
 ['match','Distraction','🌼','A pocket matching game','Turn over cards and find the matching pairs. There is no timer or penalty.',['Anywhere'],2],
 ['bubbles','Distraction','🫧','Pop a little tension','Tap a board of soft bubbles. Reset it as often as you like. No score to chase.',['Anywhere'],2],
 ['draw','Distraction','🎨','Make something without a plan','Draw loops, flowers, or a silly creature. It does not have to become anything.',['Anywhere'],2],
 ['cook','Distraction','🍳','Make a small snack','Prepare something simple you enjoy. Pay attention to the smell, texture, and first bite.',['Home'],10],
 ['rest','Rest','😴','A screen-free pause','Put the phone down, rest your eyes, and find a supported position. Let yourself do nothing for a little while.',['Anywhere'],2],
 ['sleep','Rest','🌙','Prepare a softer evening','Dim your lights, put a glass of water nearby, and choose one thing you can leave until tomorrow.',['Home'],10],
 ['kind','A little kindness','💛','Talk to yourself like a friend','Write: “Today was hard because…” followed by “I deserve…” Keep it gentle and specific.',['Anywhere'],2],
 ['win','A little kindness','✨','Find a tiny win','Name something you did, even if it was resting or asking for help. Save it as a little win.',['Anywhere'],2]
].map(([id,category,icon,title,text,places,min])=>({id,category,icon,title,text,places,min}));
function minutes(){return state.reset.time==='1 hour'?60:parseInt(state.reset.time,10)}
function candidates(need, duration=60, place='Anywhere') {
 return activities.filter(a=>a.category===need && a.min<=duration && (place==='Anywhere'||a.places.includes('Anywhere')||a.places.includes(place)))
 .map(a=>{const history=state.attempts.filter(x=>x.id===a.id);return {...a,score:history.length?history.filter(x=>x.result>=2).length/history.length:0.5}})
 .sort((a,b)=>b.score-a.score || b.min-a.min);
}
home = function(){
 let html=baseHome().replace('Good evening, Yuvraj','Hello, Rishika');
 ['energy','stress','socialBattery','clarity'].forEach((key,i)=>{const defaults=[32,78,38,46];html=html.replace(`type="range" value="${defaults[i]}"`,`type="range" value="${check[key]}"`).replace(`<output>${defaults[i]}</output>`,`<output>${check[key]}</output>`)});
 html=html.replace('Friday, 2 October',new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Kolkata'}).format(new Date()));
 if(state.checked){const emoji=weather.find(x=>x[1]===check.weather)?.[0]||'🌤';html=html.replace('🌧 Heavy + drained',`${emoji} ${escapeHtml(check.weather)}`).replace('Sounds like today has taken a lot out of you.','Thanks for making a little room for how you feel.').replace('Energy 32%',`Energy ${check.energy}%`).replace('Stress 78%',`Stress ${check.stress}%`).replace('Social 38%',`Social ${check.socialBattery}%`);html=html.replace('</h2><p class="sub"', '</h2><button class="text-btn" data-action="recheck">Check in again</button><p class="sub"');}
 return html+`<h2 class="section-title">A little room for play</h2><button class="action-card" data-action="games"><span class="icon">🎮</span><div><b>Pocket games</b><p>Match flowers, pop bubbles, or breathe along.</p></div></button>`;
};
softLanding = function(){const list=candidates(state.need);const selected=Array.from({length:Math.min(3,list.length)},(_,i)=>list[(i+state.rotation)%list.length]);return `<div class="card soft-landing"><div class="eyebrow">A little ${escapeHtml(state.need.toLowerCase())}</div><h3>${({Comfort:'Your soft landing.',Calm:'Let the moment slow down.',Energy:'A gentle change of pace.',Connection:'A little less alone.',Distraction:'Room for a little play.',Clarity:'Untangle one small thing.'})[state.need]}</h3><div class="recommend">${selected.map(a=>`<button class="action-card" data-activity="${a.id}"><span class="icon">${a.icon}</span><div><b>${a.title}</b><p>${escapeHtml(a.text.slice(0,72))}…</p></div></button>`).join('')}</div><button class="text-btn" data-action="another">Give me another →</button></div>`};
me = function(){return baseMe().replace('<div class="avatar">Y</div>','<div class="avatar">R</div>').replace('Yuvraj','Rishika').replace('<button class="menu-item"><span>🫂','<button class="menu-item" data-action="social"><span>🫂').replace('<button class="menu-item"><span>🎨','<button class="menu-item" data-action="nutrition"><span>🎨').replace('<button class="menu-item"><span>⚙','<button class="menu-item" data-action="settings"><span>⚙')};
reset = function(){return baseReset()+`<button class="ghost full" style="width:100%;margin-top:12px" data-action="games">🎮 Try a pocket game</button>`};
bind = function(){baseBind();$$('.sliders input').forEach((input,i)=>input.oninput=()=>{input.nextElementSibling.value=input.value;check[['energy','stress','socialBattery','clarity'][i]]=Number(input.value)});$$('[data-activity]').forEach(b=>b.onclick=()=>showActivity(b.dataset.activity));$$('[data-play-song]').forEach(b=>b.onclick=()=>playSong(songs.find(s=>s.title===b.dataset.playSong)||{title:b.dataset.playSong,id:b.dataset.songId}));const search=$('.search');if(search)search.oninput=()=>{const query=search.value.toLowerCase();$$('.entry').forEach(e=>e.hidden=!e.textContent.toLowerCase().includes(query))};};
action = function(a){
 if(a==='recheck'){state.checked=false;render();return}
 if(a==='checkin'){const inputs=$$('.sliders input');['energy','stress','socialBattery','clarity'].forEach((key,i)=>check[key]=Number(inputs[i]?.value||check[key]));check.weather=state.weather;check.note=$('.note-input')?.value||'';check.date=new Date().toISOString();if(!safeSave('checkin',check))return;}
 if(a==='another'){state.rotation++;render();return}
 if(a==='social'){socialScreen();return}if(a==='nutrition'){nutritionScreen();return}if(a==='settings'){settingsScreen();return}
 if(a==='games'){gamesScreen();return}if(a==='scrapbook'){editor('scrapbook');return}
 if(a==='song'){playSong(songs[2]);return}
 baseAction(a);
};
closeModal = function(){clearInterval(resetTimer);resetTimer=null;baseClose()};
function sheetHead(title,label='Your little world'){return `<div class="sheet-head"><div><div class="eyebrow">${label}</div><h2>${title}</h2></div><button class="close" aria-label="Close">×</button></div>`}
function safeSave(key,value){try{store.set(key,value);return true}catch{toast('Storage is full. Try fewer photos or export your data in Settings.');return false}}
function showActivity(id){const a=activities.find(x=>x.id===id);if(!a)return;if(id==='match'||id==='bubbles'||id==='breath'){game(id);return}if(id==='draw'){editor('scrapbook');return}if(id==='letter'){letter();return}modal(`${sheetHead(a.title,a.category)}<div class="card result-card"><div style="font-size:48px">${a.icon}</div><p class="sub">${a.text}</p></div><button class="primary full" id="try-activity">Try this reset →</button>`);$('#try-activity').onclick=()=>{state.reset.need=a.category;activeReset=a;resetResult(a)}}
resetResult = function(chosen){const list=candidates(state.reset.need,minutes(),state.reset.place);activeReset=chosen||list[state.rotation%list.length]||activities.find(a=>a.category===state.reset.need);const a=activeReset;modal(`${sheetHead(a.title,`Your ${escapeHtml(state.reset.time)} ${escapeHtml(a.category.toLowerCase())} reset`)}<div class="card result-card"><div class="result-step"><b>${a.icon}</b><div><strong>${a.title}</strong><p class="sub">${a.text}</p></div></div><div class="result-step"><b>📍</b><div><strong>${escapeHtml(state.reset.place)}</strong><p class="sub">Take this at your own pace. Use your available time; a short pause counts too.</p></div></div><div class="result-step"><b>🌱</b><div><strong>Notice what changed</strong><p class="sub">When you return, tell us how it felt.</p></div></div></div><button class="primary full" id="start-timer">Start ${escapeHtml(state.reset.time)}</button><button class="text-btn" id="other-reset">Try a different idea →</button>${['match','bubbles','breath'].includes(a.id)?'<button class="ghost" id="open-game">Open activity</button>':''}`);$('#other-reset').onclick=()=>{state.rotation++;resetResult()};if($('#open-game'))$('#open-game').onclick=()=>game(a.id);$('#start-timer').onclick=()=>startTimer(a)};
function startTimer(a){let end=Date.now()+minutes()*60000;modal(`${sheetHead(a.title,'Your reset is in motion')}<div style="text-align:center;padding:20px"><div style="font-size:58px">${a.icon}</div><div class="timer" id="countdown"></div><p class="sub">${a.text}</p><button class="primary full" id="finish">I'm back</button></div>`);const tick=()=>{let remaining=Math.max(0,Math.ceil((end-Date.now())/1000));if(!$('#countdown'))return;$('#countdown').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(!remaining){clearInterval(resetTimer);feedback()}};tick();resetTimer=setInterval(tick,1000);$('#finish').onclick=()=>{clearInterval(resetTimer);feedback()}}
feedback = function(){modal(`${sheetHead('How are you feeling now?','After your reset')}<div class="choice-grid">${['😞 Worse','😐 Same','🙂 Better','😊 Much better'].map((x,i)=>`<button class="big-choice" data-feedback="${i}">${x}</button>`).join('')}</div>`);$$('[data-feedback]').forEach(b=>b.onclick=()=>{const attempt={id:activeReset?.id||'pause',category:activeReset?.category||state.reset.need,result:Number(b.dataset.feedback),date:new Date().toISOString()};const next=[...state.attempts,attempt];if(!safeSave('attempts',next))return;state.attempts=next;closeModal();toast('Saved. Your next suggestions will learn from this.');render()})};

function spotifyId(value){const match=String(value).trim().match(/^(?:https:\/\/open\.spotify\.com\/(?:intl-[a-z]+\/)?|spotify:)(track|album|playlist)[/:]([a-zA-Z0-9]{22})(?:\?.*)?$/);return match?{type:match[1],id:match[2]}:null}
function embedSong(song){const type=['track','album','playlist'].includes(song.type)?song.type:'track';return /^[a-zA-Z0-9]{22}$/.test(song.id||'')?`<iframe class="spotify-player" title="Spotify: ${escapeHtml(song.title)}" src="https://open.spotify.com/embed/${type}/${song.id}" width="100%" height="152" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe><a class="text-btn" href="https://open.spotify.com/${type}/${song.id}" target="_blank" rel="noopener">Open in Spotify ↗</a>`:''}
function playSong(song){modal(`${sheetHead(escapeHtml(song.title||'Your song'),'Sounds like you')}${embedSong(song)||'<p class="sub">Choose a song or paste its Spotify share link to listen.</p>'}<p class="tiny">Tap Play in the Spotify player. Internet is needed; Spotify may offer a preview or ask you to sign in.</p>`)}
function songPicker(){const box=$('#tool-panel');box.innerHTML=`<h3>Find today's song</h3><input class="search" id="song-search" placeholder="Search the small song collection…"><div id="song-results"></div><label class="sub" for="spotify-link">Or paste a Spotify track, album, or playlist link</label><input class="search" id="spotify-link" placeholder="https://open.spotify.com/track/…"><button class="ghost" id="attach-link">Attach Spotify link</button><p id="song-error" role="status" class="tiny"></p>`;const results=()=>{$('#song-results').innerHTML=songs.filter(s=>(s.title+' '+s.artist).toLowerCase().includes($('#song-search').value.toLowerCase())).map(s=>`<button class="action-card" style="width:100%;margin-bottom:8px" data-song="${s.id}"><span class="icon">♫</span><div><b>${s.title}</b><p>${s.artist}</p></div></button>`).join('');$$('[data-song]').forEach(b=>b.onclick=()=>attachSong(songs.find(s=>s.id===b.dataset.song)))};results();$('#song-search').oninput=results;$('#attach-link').onclick=()=>{const parsed=spotifyId($('#spotify-link').value);if(!parsed){$('#song-error').textContent='Use a full open.spotify.com track, album, or playlist link from Share → Copy link.';return}attachSong({...parsed,title:'My Spotify pick',artist:'Spotify'})}}
function attachSong(song){draft.song=song;$('#tool-panel').innerHTML='';$('#song-preview').innerHTML=embedSong(song)+`<button class="text-btn" id="remove-song">Remove song</button>`;$('#remove-song').onclick=()=>{draft.song=null;$('#song-preview').innerHTML=''}}
editor = function(mode=false){mode=mode===true?'photo':mode===false?'write':mode;draft={mode,photos:[],stickers:[],song:null,doodle:null};modal(`${sheetHead(mode==='photo'?'Your day in photos':mode==='scrapbook'?'Make a little scrapbook':'Capture this moment','New moment')}<div class="editor"><div class="editor-tools"><button class="tool" data-tool="text">Aa Text</button><button class="tool" data-tool="photo">📷 Photo</button><button class="tool" data-tool="song">♫ Song</button><button class="tool" data-tool="sticker">⭐ Sticker</button><button class="tool" data-tool="doodle">〰 Doodle</button></div><input hidden type="file" id="photo-files" accept="image/*" multiple><div id="photo-preview" class="attachment-grid"></div>${mode==='photo'?'<button class="upload-area" id="add-photos">＋ Add 1–6 photos</button>':''}<div class="scrap-paper"><div id="sticker-preview" class="sticker-preview"></div><textarea id="entry-text" placeholder="What would you want to remember?"></textarea><img id="doodle-preview" class="doodle-preview" hidden alt="Your drawing"></div><div id="song-preview"></div><div id="tool-panel"></div><label class="sub" for="entry-weather">Today's weather</label><select id="entry-weather" class="search">${weather.map(([e,n])=>`<option ${n===state.weather?'selected':''}>${e} ${n}</option>`).join('')}</select><label class="tag"><input type="checkbox" id="win"> ✦ This was a little win</label><button class="primary full" id="save-entry">Save this moment</button></div>`);if($('#add-photos'))$('#add-photos').onclick=()=>$('#photo-files').click();$$('[data-tool]').forEach(b=>b.onclick=()=>{if(b.dataset.tool==='text')$('#entry-text').focus();if(b.dataset.tool==='photo')$('#photo-files').click();if(b.dataset.tool==='song')songPicker();if(b.dataset.tool==='sticker')stickerPicker();if(b.dataset.tool==='doodle')doodleTool()});$('#photo-files').onchange=uploadPhotos;$('#save-entry').onclick=saveEntry;}
async function uploadPhotos(event){const files=[...event.target.files];if(files.length+draft.photos.length>6){toast('Choose up to six photos per moment.');return}$('#save-entry').disabled=true;try{for(const file of files){if(!file.type.startsWith('image/'))continue;draft.photos.push(await compressPhoto(file));}renderPhotos()}catch{toast('Could not read that photo. Try a JPEG or PNG.')}finally{$('#save-entry').disabled=false;event.target.value=''}}
function compressPhoto(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image();image.onload=()=>{const scale=Math.min(1,1000/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',0.72))};image.onerror=()=>{URL.revokeObjectURL(url);reject()};image.src=url})}
function renderPhotos(){$('#photo-preview').innerHTML=draft.photos.map((src,i)=>`<div class="attachment"><img src="${src}" alt="Attached photo ${i+1}"><button class="remove-attachment" data-remove-photo="${i}" aria-label="Remove photo">×</button></div>`).join('');$$('[data-remove-photo]').forEach(b=>b.onclick=()=>{draft.photos.splice(Number(b.dataset.removePhoto),1);renderPhotos()})}
function stickerPicker(){$('#tool-panel').innerHTML=`<h3>A little decoration</h3><p class="tiny">Tap to add. Tap an added sticker to remove it.</p><div class="sticker-tray">${['⭐','🌼','🌷','☁️','🫶','🎀','🍒','🌙','💌','🧸','🪩','🌈','✨','❤️','🍃','🦋'].map(s=>`<button class="sticker-button" data-sticker="${s}">${s}</button>`).join('')}</div>`;$$('[data-sticker]').forEach(b=>b.onclick=()=>{if(draft.stickers.length>=12){toast('Twelve little stickers is plenty for one page.');return}draft.stickers.push(b.dataset.sticker);renderStickers()})}
function renderStickers(){$('#sticker-preview').innerHTML=draft.stickers.map((s,i)=>`<button class="sticker-button" data-remove-sticker="${i}" aria-label="Remove ${s}">${s}</button>`).join('');$$('[data-remove-sticker]').forEach(b=>b.onclick=()=>{draft.stickers.splice(Number(b.dataset.removeSticker),1);renderStickers()})}
function doodleTool(){$('#tool-panel').innerHTML=`<h3>A doodle, just because</h3><div class="editor-tools"><input type="color" id="pen-color" value="#7b669d" aria-label="Pen colour"><button class="tool" id="clear-doodle">Clear</button><button class="tool" id="keep-doodle">Keep drawing</button></div><canvas id="drawing" width="600" height="360" aria-label="Draw with your finger or mouse"></canvas>`;const canvas=$('#drawing'),ctx=canvas.getContext('2d');ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';if(draft.doodle){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,600,360);img.src=draft.doodle}let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height]};const save=()=>{draft.doodle=canvas.toDataURL('image/png');$('#doodle-preview').src=draft.doodle;$('#doodle-preview').hidden=false};canvas.onpointerdown=e=>{drawing=true;canvas.setPointerCapture(e.pointerId);ctx.strokeStyle=$('#pen-color').value;ctx.beginPath();ctx.moveTo(...point(e));};canvas.onpointermove=e=>{if(drawing){ctx.lineTo(...point(e));ctx.stroke();save()}};canvas.onpointerup=canvas.onpointercancel=()=>{drawing=false;save()};$('#clear-doodle').onclick=()=>{ctx.clearRect(0,0,600,360);draft.doodle=null;$('#doodle-preview').hidden=true};$('#keep-doodle').onclick=()=>{save();$('#tool-panel').innerHTML=''}}
function saveEntry(){if(draft.mode==='photo'&&!draft.photos.length){toast('Add at least one photo to your photo dump.');return}const text=$('#entry-text').value.trim();if(!text&&!draft.photos.length&&!draft.doodle&&!draft.stickers.length&&!draft.song){toast('Add a thought, photo, song, or decoration first.');return}const entry={id:crypto.randomUUID(),date:new Date().toISOString(),day:'Just now',weather:$('#entry-weather').value,text,photos:draft.photos,stickers:draft.stickers,doodle:draft.doodle,type:draft.mode,song:draft.song?.title||'',songData:draft.song,tag:$('#win').checked?'Little win':'A moment'};const next=[entry,...state.entries];if(!safeSave('entries',next))return;state.entries=next;closeModal();state.tab='journal';render();toast('Your moment, tucked away ✦')}
journal = function(){return `<header class="top"><div class="headline-row"><div><div class="eyebrow">Journal</div><h1 class="greeting">Your life, as it felt.</h1></div><button class="ghost" data-action="new" aria-label="New moment">＋</button></div></header><input class="search" placeholder="Search your world…" aria-label="Search journal"><div class="create-options"><button class="create-option" data-action="new"><b>✎</b>Write</button><button class="create-option" data-action="photo"><b>📷</b>Photo dump</button><button class="create-option" data-action="scrapbook"><b>✦</b>Scrapbook</button></div><h2 class="section-title">Little moments</h2><div class="timeline">${state.entries.map(e=>`<article class="card entry"><div class="entry-meta"><span>${escapeHtml(e.day)}</span><span>${escapeHtml(e.weather)}</span></div>${e.photos?.length?`<div class="attachment-grid">${e.photos.filter(src=>/^data:image\/(jpeg|png|webp);base64,/.test(src)).map(src=>`<img class="saved-photo" src="${src}" alt="A photo from this moment">`).join('')}</div>`:''}<div class="saved-stickers">${(e.stickers||[]).map(escapeHtml).join(' ')}</div><p class="entry-quote">${escapeHtml(e.text)}</p>${e.doodle&&/^data:image\/png;base64,/.test(e.doodle)?`<img class="doodle-preview" src="${e.doodle}" alt="Saved doodle">`:''}<div class="tags">${e.song?`<button class="tag song-tag" data-play-song="${escapeHtml(e.song)}" data-song-id="${escapeHtml(e.songData?.id||'')}">▶ ${escapeHtml(e.song)}</button>`:''}<span class="tag">${escapeHtml(e.tag)}</span></div></article>`).join('')}</div>`};

function socialScreen(){modal(`${sheetHead('Your social rhythm','People and energy')}<p class="sub">Notice how different moments affect your energy. Your own logs appear below.</p><div class="card pattern-card"><p class="sub">${state.social.length?`${state.social.length} moments logged`:'No personal social logs yet. Add a moment to start noticing patterns.'}</p><div id="social-history">${state.social.map(x=>`<p class="sub">${escapeHtml(x.person||x.kind)} · ${escapeHtml(x.kind)} · ${x.before}% → ${x.after}%</p>`).join('')}</div></div><h3 class="section-title">Keep a people moment</h3><input id="social-person" class="search" placeholder="Name or nickname (optional)"><select id="social-kind" class="search">${['Close friend','Friend group','Partner','Family','Colleagues','New people'].map(x=>`<option>${x}</option>`).join('')}</select><label class="slider-line">Before<input id="social-before" type="range" value="40"><output>40</output></label><label class="slider-line">After<input id="social-after" type="range" value="60"><output>60</output></label><button class="primary full" id="save-social">Save social moment</button>`);$$('.sheet input[type=range]').forEach(i=>i.oninput=()=>i.nextElementSibling.value=i.value);$('#save-social').onclick=()=>{const next=[...state.social,{person:$('#social-person').value,kind:$('#social-kind').value,before:Number($('#social-before').value),after:Number($('#social-after').value),date:new Date().toISOString()}];if(!safeSave('social',next))return;state.social=next;socialScreen();toast('A little pattern, remembered.')}}
const nutritionTypes=['Connection','Play','Rest','Outdoors','Movement','Meaningful work','Solitude','Novelty'];
function nutritionScreen(){const recent=state.nutrition.filter(x=>Date.now()-new Date(x.date).getTime()<7*86400000);modal(`${sheetHead('What has filled your week?','Mental nutrition')}<p class="sub">A picture of your experiences, without targets or grades.</p>${nutritionTypes.map((x,i)=>{const n=recent.filter(a=>a.category===x).length;return `<div class="pattern-card card"><div class="headline-row"><b>${['🫂','🎨','😴','🌿','🚶','🧠','🌙','✨'][i]} ${x}</b><span>${n} moments</span></div><div class="score"><i style="width:${Math.min(100,n*20)}%"></i></div></div>`}).join('')}<p class="sub">${recent.length?'Which experience would you like a little more room for?':'Start with one experience from today. Your own weekly picture will grow here.'}</p><select class="search" id="nutrition-type">${nutritionTypes.map(x=>`<option>${x}</option>`).join('')}</select><button class="primary full" id="save-nutrition">Save an experience</button>`);$('#save-nutrition').onclick=()=>{const next=[...state.nutrition,{category:$('#nutrition-type').value,date:new Date().toISOString()}];if(!safeSave('nutrition',next))return;state.nutrition=next;nutritionScreen();toast('A little experience, kept.')}}
function settingsScreen(){modal(`${sheetHead('Your space, your data','Settings')}<p class="sub">Hello, Rishika. Your journal and photos stay in this browser. Keep a backup before changing devices.</p><button class="primary full" id="export-data">Download my journal backup</button><p class="tiny">Music uses Spotify's online player. Photos, games, and journal tools work locally.</p>`);$('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify({entries:state.entries,checkin:check,social:state.social,nutrition:state.nutrition,attempts:state.attempts},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='rishika-lumen-backup.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function gamesScreen(){modal(`${sheetHead('A little room for play','Pocket games')}<p class="sub">Choose a small pause. No streaks, no pressure.</p><div class="recommend">${[['match','🌼','Flower pairs','For a playful distraction'],['bubbles','🫧','Bubble garden','For a small release'],['breath','🌬','Breathe along','For a calmer moment']].map(([id,icon,title,sub])=>`<button class="action-card" data-game="${id}"><span class="icon">${icon}</span><div><b>${title}</b><p>${sub}</p></div></button>`).join('')}</div>`);$$('[data-game]').forEach(b=>b.onclick=()=>game(b.dataset.game))}
function game(id){activeReset=activities.find(a=>a.id===id);const footer='<button class="ghost full" id="game-back">Other games</button><button class="primary full" id="game-done">How do I feel now?</button>';if(id==='bubbles'){modal(`${sheetHead('Bubble garden','A small release')}<p class="sub">Tap the bubbles. Let each one be a little pause.</p><div class="bubble-grid">${Array.from({length:20},(_,i)=>`<button class="bubble" aria-label="Pop bubble ${i+1}">○</button>`).join('')}</div><button class="text-btn" id="more-bubbles">A fresh garden →</button>${footer}`);$$('.bubble').forEach(b=>b.onclick=()=>{b.classList.add('popped');b.disabled=true;b.textContent='✦';if($$('.bubble:not(.popped)').length===0)toast('A little space, made ✦')});$('#more-bubbles').onclick=()=>game(id)}
 if(id==='match'){let cards=['🌼','🌷','🌿','🦋','🌼','🌷','🌿','🦋'];for(let i=cards.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}modal(`${sheetHead('Flower pairs','A playful distraction')}<p class="sub" id="match-status">Find four pairs, at your own pace.</p><div class="match-grid">${cards.map((c,i)=>`<button class="match-card" data-card="${i}" aria-label="Reveal card ${i+1}">✿</button>`).join('')}</div><button class="text-btn" id="again-match">Shuffle again →</button>${footer}`);let first=null,locked=false,pairs=0;$$('[data-card]').forEach(b=>b.onclick=()=>{if(locked||b.disabled||b===first)return;b.textContent=cards[Number(b.dataset.card)];b.classList.add('flipped');if(!first){first=b;return}let previous=first;first=null;if(previous.textContent===b.textContent){b.disabled=previous.disabled=true;pairs++;$('#match-status').textContent=pairs===4?'All four pairs found. A tiny win!':`${pairs} of 4 pairs found.`}else{locked=true;setTimeout(()=>{if(b.isConnected){b.textContent=previous.textContent='✿';b.classList.remove('flipped');previous.classList.remove('flipped')}locked=false},800)}});$('#again-match').onclick=()=>game(id)}
 if(id==='breath'){modal(`${sheetHead('Breathe along','A calmer moment')}<p class="sub">Follow a gentle rhythm: in for 4 seconds, out for 6. Breathe normally whenever you like.</p><div class="breathing-circle"><span id="breath-label">Breathe in</span></div>${footer}`);let start=Date.now();resetTimer=setInterval(()=>{if($('#breath-label'))$('#breath-label').textContent=(Date.now()-start)%10000<4000?'Breathe in':'Breathe out'},200)}
 $('#game-back').onclick=()=>{clearInterval(resetTimer);gamesScreen()};$('#game-done').onclick=()=>{clearInterval(resetTimer);feedback()};
}
window.closeModal=closeModal;
if('serviceWorker' in navigator)navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!sessionStorage.getItem('lumen-v3-loaded')){sessionStorage.setItem('lumen-v3-loaded','yes');location.reload()}});
render();
